{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis-node-sensor.fullname" . }}
  labels:
    {{- include "aegis-node-sensor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.apiToken }}
  AEGIS_API_TOKEN: {{ .Values.secret.apiToken | quote }}
  {{- end }}
{{- end }}
