import type { EntityKind, FieldDescriptor } from "./types";

export const ALL_ENTITY_KINDS: ReadonlyArray<EntityKind> = [
  "ase",
  "decision",
  "incident",
  "alert",
  "approval",
  "agent",
  "mcp_server",
  "receipt",
  "rule",
];

export const FIELD_CATALOGS: Readonly<Record<EntityKind, ReadonlyArray<FieldDescriptor>>> = {
  ase: [
    { name: "timestamp", type: "time", facetable: false },
    { name: "event_type", type: "string", facetable: true, examples: ["decision_recorded", "egress_denied"] },
    { name: "severity", type: "string", facetable: true, examples: ["low", "medium", "high", "critical"] },
    { name: "source_component", type: "string", facetable: true, examples: ["gateway", "egress-proxy", "mcp"] },
    { name: "agent_id", type: "string", facetable: true },
    { name: "tool", type: "string", facetable: true },
    { name: "action", type: "string", facetable: true },
    { name: "resource", type: "string", facetable: true },
    { name: "decision", type: "decision", facetable: true, examples: ["allow", "deny", "require_approval"] },
    { name: "source_trust", type: "trust", facetable: true },
    { name: "action_hash", type: "hash", facetable: false },
    { name: "receipt_hash", type: "hash", facetable: false },
    { name: "run_id", type: "string", facetable: true },
    { name: "trace_id", type: "string", facetable: true },
  ],
  decision: [
    { name: "id", type: "string", facetable: false },
    { name: "created_at", type: "time", facetable: false },
    { name: "decision", type: "decision", facetable: true, examples: ["allow", "deny", "require_approval"] },
    { name: "source_trust", type: "trust", facetable: true, examples: ["untrusted_external", "trusted_internal_signed"] },
    { name: "root_trust_level", type: "trust", facetable: true },
    { name: "tool", type: "string", facetable: true },
    { name: "action", type: "string", facetable: true },
    { name: "resource", type: "string", facetable: true },
    { name: "agent_id", type: "string", facetable: true },
    { name: "run_id", type: "string", facetable: true },
    { name: "trace_id", type: "string", facetable: true },
    { name: "action_hash", type: "hash", facetable: false },
    { name: "receipt_hash", type: "hash", facetable: false },
    { name: "matched_policy_ids", type: "json", facetable: false },
    { name: "reason", type: "string", facetable: false },
    { name: "composite_risk_score", type: "number", facetable: false },
  ],
  incident: [
    { name: "id", type: "string", facetable: false },
    { name: "kind", type: "string", facetable: true },
    { name: "severity", type: "string", facetable: true, examples: ["low", "medium", "high", "critical"] },
    { name: "status", type: "string", facetable: true, examples: ["open", "investigating", "resolved"] },
    { name: "agent_id", type: "string", facetable: true },
    { name: "summary", type: "string", facetable: false },
    { name: "opened_at", type: "time", facetable: false },
    { name: "closed_at", type: "time", facetable: false },
  ],
  alert: [
    { name: "id", type: "string", facetable: false },
    { name: "alert_id", type: "string", facetable: false },
    { name: "rule", type: "string", facetable: true },
    { name: "severity", type: "string", facetable: true, examples: ["low", "medium", "high", "critical"] },
    { name: "status", type: "string", facetable: true, examples: ["open", "closed"] },
    { name: "agent_id", type: "string", facetable: true },
    { name: "source_event_id", type: "string", facetable: false },
    { name: "summary", type: "string", facetable: false },
    { name: "occurred_at", type: "time", facetable: false },
    { name: "created_at", type: "time", facetable: false },
  ],
  approval: [
    { name: "id", type: "string", facetable: false },
    { name: "approval_id", type: "string", facetable: false },
    { name: "decision_id", type: "string", facetable: false },
    { name: "status", type: "string", facetable: true, examples: ["created", "approved", "rejected", "expired"] },
    { name: "tool_name", type: "string", facetable: true },
    { name: "agent_id", type: "string", facetable: true },
    { name: "run_id", type: "string", facetable: true },
    { name: "trace_id", type: "string", facetable: true },
    { name: "source_trust", type: "trust", facetable: true },
    { name: "action_hash", type: "hash", facetable: false },
    { name: "original_action_hash", type: "hash", facetable: false },
    { name: "edited_action_hash", type: "hash", facetable: false },
    { name: "effective_action_hash", type: "hash", facetable: false },
    { name: "expires_at", type: "time", facetable: false },
    { name: "approver_group", type: "string", facetable: true },
    { name: "risk_score", type: "number", facetable: false },
    { name: "reason", type: "string", facetable: false },
  ],
  agent: [
    { name: "id", type: "string", facetable: false },
    { name: "agent_id", type: "string", facetable: false },
    { name: "status", type: "string", facetable: true, examples: ["active", "frozen", "quarantined"] },
    { name: "risk_tier", type: "string", facetable: true, examples: ["low", "medium", "high"] },
    { name: "last_seen", type: "time", facetable: false },
    { name: "created_at", type: "time", facetable: false },
  ],
  mcp_server: [
    { name: "server_key", type: "string", facetable: false },
    { name: "status", type: "string", facetable: true, examples: ["active", "quarantined", "disabled"] },
    { name: "transport", type: "string", facetable: true, examples: ["stdio", "http", "sse"] },
    { name: "manifest_hash", type: "hash", facetable: false },
    { name: "created_at", type: "time", facetable: false },
    { name: "updated_at", type: "time", facetable: false },
  ],
  receipt: [
    { name: "id", type: "string", facetable: false },
    { name: "created_at", type: "time", facetable: false },
    { name: "ts", type: "time", facetable: false },
    { name: "tenant_id", type: "string", facetable: false },
    { name: "agent_id", type: "string", facetable: true },
    { name: "run_id", type: "string", facetable: true },
    { name: "trace_id", type: "string", facetable: true },
    { name: "decision", type: "decision", facetable: true },
    { name: "tool", type: "string", facetable: true },
    { name: "action_hash", type: "hash", facetable: false },
    { name: "prev_receipt_hash", type: "hash", facetable: false },
    { name: "receipt_hash", type: "hash", facetable: false },
  ],
  rule: [
    { name: "id", type: "string", facetable: false },
    { name: "rule_key", type: "string", facetable: true },
    { name: "name", type: "string", facetable: false },
    { name: "severity", type: "string", facetable: true, examples: ["low", "medium", "high", "critical"] },
    { name: "source", type: "string", facetable: true, examples: ["built-in", "tenant"] },
    { name: "enabled", type: "string", facetable: true, examples: ["true", "false"] },
    { name: "condition", type: "json", facetable: false },
    { name: "created_at", type: "time", facetable: false },
    { name: "updated_at", type: "time", facetable: false },
  ],
};

export function fieldsForEntity(entity: EntityKind): ReadonlyArray<FieldDescriptor> {
  return FIELD_CATALOGS[entity];
}

export function facetableFieldsForEntity(entity: EntityKind): ReadonlyArray<FieldDescriptor> {
  return fieldsForEntity(entity).filter((field) => field.facetable);
}
