apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis-tool-broker.fullname" . }}
  labels:
    {{- include "aegis-tool-broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "aegis-tool-broker.selectorLabels" . | nindent 4 }}
