apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aegis-gateway.fullname" . }}-policy
  labels:
    {{- include "aegis-gateway.labels" . | nindent 4 }}
data:
  policies.cedar: |
{{- if .Values.cedarPolicy }}
{{ .Values.cedarPolicy | indent 4 }}
{{- else }}
{{ .Files.Get "files/policies.cedar" | indent 4 }}
{{- end }}
