{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis-gateway.fullname" . }}
  labels:
    {{- include "aegis-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.jwtSecret }}
  AEGIS_JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secret.policySigningKey }}
  AEGIS_POLICY_SIGNING_KEY: {{ .Values.secret.policySigningKey | quote }}
  {{- end }}
  {{- if .Values.secret.githubWebhookSecret }}
  AEGIS_GITHUB_WEBHOOK_SECRET: {{ .Values.secret.githubWebhookSecret | quote }}
  {{- end }}
{{- end }}
