#![no_main]

use arbitrary::Arbitrary;
use libfuzzer_sys::fuzz_target;
use serde::Serialize;

// A small recursive mirror of `serde_json::Value` that can be generated by
// `arbitrary`, bounded in depth to keep inputs finite.
#[derive(Debug, Arbitrary)]
enum ArbitraryJson {
    Null,
    Bool(bool),
    Number(i64),
    String(String),
    Array(Vec<(String, ArbitraryLeaf)>),
    Object(Vec<(String, ArbitraryLeaf)>),
}

#[derive(Debug, Arbitrary)]
enum ArbitraryLeaf {
    Null,
    Bool(bool),
    Number(i64),
    String(String),
}

impl From<ArbitraryLeaf> for serde_json::Value {
    fn from(leaf: ArbitraryLeaf) -> Self {
        match leaf {
            ArbitraryLeaf::Null => serde_json::Value::Null,
            ArbitraryLeaf::Bool(b) => serde_json::Value::Bool(b),
            ArbitraryLeaf::Number(n) => serde_json::Value::from(n),
            ArbitraryLeaf::String(s) => serde_json::Value::String(s),
        }
    }
}

impl From<ArbitraryJson> for serde_json::Value {
    fn from(value: ArbitraryJson) -> Self {
        match value {
            ArbitraryJson::Null => serde_json::Value::Null,
            ArbitraryJson::Bool(b) => serde_json::Value::Bool(b),
            ArbitraryJson::Number(n) => serde_json::Value::from(n),
            ArbitraryJson::String(s) => serde_json::Value::String(s),
            ArbitraryJson::Array(items) => {
                serde_json::Value::Array(items.into_iter().map(|(_, v)| v.into()).collect())
            }
            ArbitraryJson::Object(entries) => serde_json::Value::Object(
                entries.into_iter().map(|(k, v)| (k, v.into())).collect(),
            ),
        }
    }
}

// Mirrors `models::AuthorizeToolCall` (fields, not behavior) so the fuzzer
// can exercise `aegis_canon::canonical_value_string` (TEST-002, #1162)
// without depending on the gateway binary crate.
#[derive(Debug, Arbitrary, Serialize)]
struct FuzzToolCall {
    tool: String,
    action: String,
    resource: Option<String>,
    mutates_state: bool,
    #[arbitrary(with = arbitrary_json_value)]
    parameters: serde_json::Value,
}

fn arbitrary_json_value(u: &mut arbitrary::Unstructured) -> arbitrary::Result<serde_json::Value> {
    let value: ArbitraryJson = u.arbitrary()?;
    Ok(value.into())
}

// Must never panic for any input — `canonical_value_string` returns an empty
// string on serialization failure (fail-closed), but never panics.
fuzz_target!(|tool_call: FuzzToolCall| {
    let _ = aegis_canon::canonical_value_string(&tool_call);
});
